spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/coupon
    username: root
    password: 1234
    auto-commit: false
    connectionTimeout: 3000
    maxLifeTime: 50000
    maximumPoolSize: 30
    poolName: Hikari-coupon
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none  # 테이블 생성을 위해 create로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 사용
        default_batch_fetch_size: 128
        id:
          new_generator_mappings: true
        format_sql: true
        show_sql: true
        use_sql_comments: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false

logging:
  config: classpath:logback-local.xml
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

server:
  tomcat:
    threads:
      max: 200
      min-spare: 50
    max-connections: 8192
